name: Train Known Faces

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:              # Automatically triggers on pushes to the repository
    branches:
      - main

jobs:
  train-faces:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Ensure the correct Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install face_recognition

    - name: Train known faces
      run: |
        python train_known_faces.py
      env:
        KNOWN_PEOPLE_DIR: "data"  # Provide the data directory
        OUTPUT_FILE: "encodings.pkl"

    - name: Upload encodings.pkl artifact
      uses: actions/upload-artifact@v3
      with:
        name: encodings
        path: encodings.pkl
